#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: "#about"
    weight: 20
  - name: Posts
    url: "#posts"
    weight: 22
  #  - name: Projects
  #    url: '#projects'
  #    weight: 30
  #  - name: Talks
  #    url: '#talks'
  #    weight: 40
  - name: Publications
    url: "#publications"
    weight: 50
  - name: Contact
    url: "#contact"
    weight: 60
  - name: Archive
    url: "/all-posts/"
    weight: 70
  - name: arxivtinder
    url: "/arxivtinder/"
    weight: 80

    # Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
