#!/usr/bin/env python3
"""Emit publications_gloat.typ from typst_site/assets/citations.csv."""

import csv
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CSV_PATH = REPO_ROOT / "typst_site/assets/citations.csv"
OUT_PATH = Path(__file__).resolve().parent / "publications_gloat.typ"

ARXIV_RE = re.compile(r"arXiv[:\s]*(\d+\.\d+)", re.I)


def typ_escape_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ") + '"'


def author_parts(authors_field: str) -> list[str]:
    names: list[str] = []
    for p in authors_field.split(";"):
        p = p.strip()
        if not p:
            continue
        if "," in p:
            last, first = p.split(",", 1)
            names.append(f"{first.strip()} {last.strip()}")
        else:
            names.append(p)
    return names


def fmt_authors_typ(names: list[str]) -> str:
    def esc(n: str) -> str:
        return n.replace("]", "\\]")

    return "(" + ", ".join(f"[{esc(n)}]" for n in names) + ")"


def emit_paper(row: dict) -> str:
    authors = fmt_authors_typ(author_parts(row["Authors"]))
    title = typ_escape_string(row["Title"].strip())
    pub = (row.get("Publication") or "").strip()
    year = int(row["Year"])
    published = f"datetime(year: {year}, month: 1, day: 1)"
    vol = (row.get("Volume") or "").strip()
    num = (row.get("Number") or "").strip()
    pages = (row.get("Pages") or "").strip()

    journal_line = (
        f"  journal: {typ_escape_string(pub)},"
        if pub
        else "  journal: none,"
    )
    lines = [
        "#paper(",
        f"  authors: {authors},",
        f"  title: {title},",
        journal_line,
        f"  published: {published},",
    ]
    lines.append(f"  vol: {typ_escape_string(vol)}," if vol else "  vol: none,")
    lines.append(f"  issue: {typ_escape_string(num)}," if num else "  issue: none,")
    lines.append(f"  pages: {typ_escape_string(pages)}," if pages else "  pages: none,")
    lines.append(")")
    return "\n".join(lines)


def emit_preprint(row: dict, arxiv_id: str) -> str:
    authors = fmt_authors_typ(author_parts(row["Authors"]))
    title = typ_escape_string(row["Title"].strip())
    year = int(row["Year"])
    published = f"datetime(year: {year}, month: 1, day: 1)"
    doi = f"10.48550/arXiv.{arxiv_id}"
    return "\n".join(
        [
            "#preprint(",
            f"  authors: {authors},",
            f"  title: {title},",
            '  journal: "arXiv",',
            f"  published: {published},",
            "  status: none,",
            f"  DOI: {typ_escape_string(doi)},",
            ")",
        ]
    )


def main() -> None:
    rows: list[dict] = []
    with CSV_PATH.open(newline="", encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            rows.append(row)

    rows.sort(key=lambda r: (-int(r["Year"]), r["Title"]))

    blocks: list[str] = []
    for row in rows:
        pub = row.get("Publication") or ""
        title = row.get("Title") or ""
        m = ARXIV_RE.search(pub) or ARXIV_RE.search(title)
        if m:
            blocks.append(emit_preprint(row, m.group(1)))
        else:
            blocks.append(emit_paper(row))

    header = """// Generated by gen_publications_typ.py — do not edit by hand
#import "@preview/gloat:0.1.0": paper, preprint

"""
    OUT_PATH.write_text(header + "\n\n".join(blocks) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_PATH} ({len(blocks)} entries)")


if __name__ == "__main__":
    main()
