// Generated by gen_publications_typ.py — do not edit by hand
#import "@preview/gloat:0.1.0": paper, preprint

#paper(
  authors: ([JingChun Wang], [Meenu Upadhyay], [Eric D Boittier], [Kham Lek Chaton], [Valerii Andreichev], [Mike Devereux], [Raidel Martin Barrios], [Shimoni Patel], [Sena Aydin], [Kai Töpfer]),
  title: "Cluster Models for Next‐Generation, Machine‐Learning‐Based Energy Functions for Molecular Simulations",
  journal: "Small Structures",
  published: datetime(year: 2026, month: 1, day: 1),
  vol: "7",
  issue: "2",
  pages: "e202500656",
)

#preprint(
  authors: ([Eric D Boittier], [Markus Meuwly]),
  title: "Efficient, Equivariant Predictions of Distributed Charge Models",
  journal: "arXiv",
  published: datetime(year: 2026, month: 1, day: 1),
  status: none,
  DOI: "10.48550/arXiv.2602.07234",
)

#preprint(
  authors: ([Kham Lek Chaton], [Eric D Boittier], [Mike Devereux], [Markus Meuwly]),
  title: "Explicit, Machine-Learned Two-Body Potentials for Molecular Simulations",
  journal: "arXiv",
  published: datetime(year: 2026, month: 1, day: 1),
  status: none,
  DOI: "10.48550/arXiv.2603.14466",
)

#paper(
  authors: ([Eric D Boittier], [Silvan Kaser], [Markus Meuwly]),
  title: "Roadmap to CCSD (T)-Quality Machine-Learned Potentials for Condensed Phase Simulations",
  journal: "Journal of Chemical Theory and Computation",
  published: datetime(year: 2025, month: 1, day: 1),
  vol: "21",
  issue: "18",
  pages: "8683-8698",
)

#preprint(
  authors: ([Eric D Boittier], [Silvan Käser], [Markus Meuwly]),
  title: "Towards Large-Scale Condensed Phase Simulations using Machine Learned Energy Functions",
  journal: "arXiv",
  published: datetime(year: 2025, month: 1, day: 1),
  status: none,
  DOI: "10.48550/arXiv.2506.23272",
)

#paper(
  authors: ([Wonmuk Hwang], [Steven L Austin], [Arnaud Blondel], [Eric D Boittier], [Stefan Boresch], [Matthias Buck], [Joshua Buckner], [Amedeo Caflisch], [Hao-Ting Chang], [Xi Cheng]),
  title: "CHARMM at 45: Enhancements in accessibility, functionality, and speed",
  journal: "The Journal of Physical Chemistry B",
  published: datetime(year: 2024, month: 1, day: 1),
  vol: "128",
  issue: "41",
  pages: "9976-10042",
)

#paper(
  authors: ([Kai Topfer], [Eric Boittier], [Mike Devereux], [Andrea Pasti], [Peter Hamm], [Markus Meuwly]),
  title: "Force fields for deep eutectic mixtures: application to structure, thermodynamics and 2D-Infrared spectroscopy",
  journal: "The Journal of Physical Chemistry B",
  published: datetime(year: 2024, month: 1, day: 1),
  vol: "128",
  issue: "44",
  pages: "10937-10949",
)

#paper(
  authors: ([Eric Boittier], [Kai Töpfer], [Mike Devereux], [Markus Meuwly]),
  title: "Kernel-based minimal distributed charges: A conformationally dependent ESP-model for molecular simulations",
  journal: "Journal of Chemical Theory and Computation",
  published: datetime(year: 2024, month: 1, day: 1),
  vol: "20",
  issue: "18",
  pages: "8088-8099",
)

#paper(
  authors: ([Mike Devereux], [Eric D Boittier], [Markus Meuwly]),
  title: "Systematic improvement of empirical energy functions in the era of machine learning",
  journal: "Journal of Computational Chemistry",
  published: datetime(year: 2024, month: 1, day: 1),
  vol: "45",
  issue: "22",
  pages: "1899-1913",
)

#paper(
  authors: ([Haydar Taylan Turan], [Eric Boittier], [Markus Meuwly]),
  title: "Interaction at a distance: Xenon migration in Mb",
  journal: "The Journal of Chemical Physics",
  published: datetime(year: 2023, month: 1, day: 1),
  vol: "158",
  issue: "12",
  pages: none,
)

#paper(
  authors: ([Tabassum Khair Barbhuiya], [Mark Fisher], [Eric D Boittier], [Emma Bolderson], [Kenneth J O'Byrne], [Derek J Richard], [Mark Nathaniel Adams], [Neha S Gandhi]),
  title: "Structural investigation of CDCA3‐Cdh1 p rotein–protein interactions using in vitro studies and molecular dynamics simulation",
  journal: "Protein Science",
  published: datetime(year: 2023, month: 1, day: 1),
  vol: "32",
  issue: "3",
  pages: "e4572",
)

#paper(
  authors: ([Taija L Fischer], [Margarethe Bödecker], [Sophie M Schweer], [Jennifer Dupont], [Valéria Lepère], [Anne Zehnacker-Rentien], [Martin A Suhm], [Benjamin Schröder], [Tobias Henkes], [Diego M Andrada]),
  title: "The first HyDRA challenge for computational vibrational spectroscopy",
  journal: "Physical Chemistry Chemical Physics",
  published: datetime(year: 2023, month: 1, day: 1),
  vol: "25",
  issue: "33",
  pages: "22089-22102",
)

#paper(
  authors: ([Eric D Boittier], [Mike Devereux], [Markus Meuwly]),
  title: "Molecular dynamics with conformationally dependent, distributed charges",
  journal: "Journal of Chemical Theory and Computation",
  published: datetime(year: 2022, month: 1, day: 1),
  vol: "18",
  issue: "12",
  pages: "7544-7554",
)

#paper(
  authors: ([Eric D Boittier], [Norbert Wimmer], [Alexandria K Harris], [Mark A Schembri], [Vito Ferro]),
  title: "Synthesis of a Gal-ß-(1? 4)-Gal disaccharide as a ligand for the fimbrial adhesin UcaD",
  journal: "Australian Journal of Chemistry",
  published: datetime(year: 2022, month: 1, day: 1),
  vol: "76",
  issue: "1",
  pages: "30-36",
)

#paper(
  authors: ([Luis Itza Vazquez-Salazar], [Eric D Boittier], [Markus Meuwly]),
  title: "Uncertainty quantification for predictions of atomistic neural networks",
  journal: "Chemical science",
  published: datetime(year: 2022, month: 1, day: 1),
  vol: "13",
  issue: "44",
  pages: "13068-13084",
)

#paper(
  authors: ([Katrina Kildey], [Neha S Gandhi], [Katherine B Sahin], [Esha T Shah], [Eric Boittier], [Pascal HG Duijf], [Christopher Molloy], [Joshua T Burgess], [Sam Beard], [Emma Bolderson]),
  title: "Elevating CDCA3 levels in non-small cell lung cancer enhances sensitivity to platinum-based chemotherapy",
  journal: "Communications Biology",
  published: datetime(year: 2021, month: 1, day: 1),
  vol: "4",
  issue: "1",
  pages: "638",
)

#paper(
  authors: ([Sarah-Louise Ryan], [Keyur A Dave], [Sam Beard], [Martina Gyimesi], [Matthew McTaggart], [Katherine B Sahin], [Christopher Molloy], [Neha S Gandhi], [Eric Boittier], [Connor G O’Leary]),
  title: "Identification of proteins deregulated by platinum-based chemotherapy as novel biomarkers and therapeutic targets in non-small cell lung cancer",
  journal: "Frontiers in oncology",
  published: datetime(year: 2021, month: 1, day: 1),
  vol: "11",
  issue: none,
  pages: "615967",
)

#paper(
  authors: ([Luis Itza Vazquez-Salazar], [Eric D Boittier], [Oliver T Unke], [Markus Meuwly]),
  title: "Impact of the characteristics of quantum chemical databases on machine learning prediction of tautomerization energies",
  journal: "Journal of chemical theory and computation",
  published: datetime(year: 2021, month: 1, day: 1),
  vol: "17",
  issue: "8",
  pages: "4769-4785",
)

#paper(
  authors: ([Silvan Kaser], [Eric D Boittier], [Meenu Upadhyay], [Markus Meuwly]),
  title: "Transfer learning to CCSD (T): Accurate anharmonic frequencies from machine learning models",
  journal: "Journal of Chemical Theory and Computation",
  published: datetime(year: 2021, month: 1, day: 1),
  vol: "17",
  issue: "6",
  pages: "3687-3699",
)

#paper(
  authors: ([Eric D Boittier], [Yat Yin Tang], [McKenna E Buckley], [Zachariah P Schuurs], [Derek J Richard], [Neha S Gandhi]),
  title: "Assessing molecular docking tools to guide targeted drug discovery of CD38 inhibitors",
  journal: "International journal of molecular sciences",
  published: datetime(year: 2020, month: 1, day: 1),
  vol: "21",
  issue: "15",
  pages: "5183",
)

#paper(
  authors: ([Eric D Boittier], [Jed M Burns], [Neha S Gandhi], [Vito Ferro]),
  title: "GlycoTorch Vina: docking designed and tested for glycosaminoglycans",
  journal: "Journal of Chemical Information and Modeling",
  published: datetime(year: 2020, month: 1, day: 1),
  vol: "60",
  issue: "12",
  pages: "6328-6343",
)

#paper(
  authors: ([Eric D Boittier], [Neha S Gandhi], [Vito Ferro], [Deirdre R Coombe]),
  title: "Cross-species analysis of glycosaminoglycan binding proteins reveals some animal models are “More Equal” than others",
  journal: "Molecules",
  published: datetime(year: 2019, month: 1, day: 1),
  vol: "24",
  issue: "5",
  pages: "924",
)

#paper(
  authors: ([Jed M Burns], [Eric D Boittier]),
  title: "Pathway Bifurcation in the (4 + 3)/(5 + 2)-Cycloaddition of Butadiene and Oxidopy- rylium Ylides: The Significance of Molecular Orbital Isosymmetry.",
  journal: "Journal of Organic Chemistry",
  published: datetime(year: 2019, month: 1, day: 1),
  vol: "84",
  issue: "10",
  pages: "5997-6005",
)
